@extends('layouts.app') @section('title','Beranda') @section('heading',$currentSpace->type==='family'?'Ringkasan Keluarga':'Ringkasan Pribadi') @section('content')
<div class="scope-banner"><i style="background:{{ $currentSpace->color }}"></i><span><strong>{{ $currentSpace->name }}</strong><small>{{ $currentSpace->type==='family'?'Hanya data bersama di ruang keluarga ini':'Hanya data pribadi Anda' }}</small></span><a href="{{ route('spaces.index') }}">Ganti ruang</a></div>
<section class="dashboard-overview">
    <div class="card hero dashboard-balance"><div class="eyebrow" style="color:#b9fff3">Total saldo likuid</div><div class="amount">Rp {{ number_format($accounts->sum('current_balance'),0,',','.') }}</div><p style="opacity:.8">Tersebar di {{ $accounts->count() }} sumber kas aktif</p><a class="btn btn-warm" href="{{ route('transactions.create') }}">+ Catat transaksi</a></div>
    <div class="card cashflow-wide"><div class="cashflow-heading"><div><div class="eyebrow">Ringkasan periode</div><h2>Cashflow bulan ini</h2></div><span class="badge">{{ now()->translatedFormat('F Y') }}</span></div><div class="cashflow-metrics"><div><span>Pemasukan</span><strong class="positive">Rp {{ number_format($monthTotals['income']??0,0,',','.') }}</strong></div><div><span>Pengeluaran</span><strong class="negative">Rp {{ number_format($monthTotals['expense']??0,0,',','.') }}</strong></div><div><span>Selisih bersih</span>@php($monthNet=($monthTotals['income']??0)-($monthTotals['expense']??0))<strong class="{{ $monthNet<0?'negative':'positive' }}">Rp {{ number_format($monthNet,0,',','.') }}</strong></div></div></div>
</section>
<section class="health-card health-{{ $financialHealth['severity'] }}" style="margin-top:18px">
    <div class="health-icon">{{ $financialHealth['severity']==='healthy'?'✓':'!' }}</div>
    <div><div class="eyebrow">Indikator kesehatan keuangan</div><h2>{{ $financialHealth['severity']==='healthy'?'Keuangan dalam kondisi baik':($financialHealth['severity']==='critical'?'Perlu tindakan segera':'Perlu perhatian') }}</h2>
    @if($financialHealth['issues']->isEmpty())<p>Cashflow, saldo, dan penggunaan anggaran bulan ini masih terkendali.</p>@else<ul>@foreach($financialHealth['issues'] as $issue)<li><a href="{{ $issue['url'] }}"><strong>{{ $issue['title'] }}</strong> — {{ $issue['message'] }}</a></li>@endforeach</ul>@endif</div>
</section>
<section class="grid grid-2" style="margin-top:18px"><div class="card"><div class="actions" style="justify-content:space-between"><div><div class="eyebrow">Enam bulan</div><h2>Arus uang</h2></div><span class="badge">Hijau masuk · Jingga keluar</span></div>@php($max=max(1,$trend->max(fn($x)=>max($x['income'],$x['expense']))))<div class="bars">@foreach($trend as $item)<div class="bar-group"><i class="bar bar-income" style="height:{{ $item['income']/$max*100 }}%"></i><i class="bar bar-expense" style="height:{{ $item['expense']/$max*100 }}%"></i><span class="bar-label">{{ $item['label'] }}</span></div>@endforeach</div></div><div class="card"><div class="eyebrow">Pengeluaran terbesar</div><h2>Bulan ini</h2>@forelse($topCategories as $cat)<div class="row"><i style="width:10px;height:10px;border-radius:50%;background:{{ $cat->color }}"></i><span>{{ $cat->name }}</span><strong>Rp {{ number_format($cat->total,0,',','.') }}</strong></div>@empty<div class="empty">Belum ada pengeluaran bulan ini.</div>@endforelse</div></section>
<section class="grid grid-2" style="margin-top:18px"><div class="card"><div class="actions" style="justify-content:space-between"><h2>Sumber kas</h2><a class="btn btn-soft" href="{{ route('accounts.index') }}">Lihat semua</a></div><div class="grid grid-2">@forelse($accounts->take(4) as $account)<a href="{{ route('accounts.show',$account) }}" class="account-card" style="background:linear-gradient(135deg,{{ $account->color }},color-mix(in srgb,{{ $account->color }} 65%,#102d29))"><span>{{ $account->name }}</span><strong style="font-size:20px">Rp {{ number_format($account->current_balance,0,',','.') }}</strong><small>{{ strtoupper($account->type) }}</small></a>@empty<div class="empty"><p>Belum ada sumber kas.</p><a class="btn btn-primary" href="{{ route('accounts.create') }}">Tambah sekarang</a></div>@endforelse</div></div><div class="card"><div class="actions" style="justify-content:space-between"><h2>Transaksi terbaru</h2><a class="btn btn-soft" href="{{ route('transactions.index') }}">Semua</a></div>@forelse($recent as $transaction)<x-transaction-row :transaction="$transaction"/>@empty<div class="empty">Transaksi pertama Anda akan tampil di sini.</div>@endforelse</div></section>
@if($budgets->isNotEmpty())<section class="card" style="margin-top:18px"><div class="eyebrow">Anggaran aktif</div><h2>Jaga pengeluaran tetap terkendali</h2><div class="grid grid-3">@foreach($budgets as $budget)@php($pct=min(100,round($budget->spent/$budget->limit_amount*100)))<div><div class="actions" style="justify-content:space-between"><strong>{{ $budget->category->name }}</strong><span>{{ $pct }}%</span></div><div class="progress"><i style="width:{{ $pct }}%;background:{{ $pct>=100?'var(--danger)':($pct>=70?'var(--warm)':'var(--brand)') }}"></i></div><small class="muted">Rp {{ number_format($budget->spent,0,',','.') }} / Rp {{ number_format($budget->limit_amount,0,',','.') }}</small></div>@endforeach</div></section>@endif
@endsection
